title: Tom Preston-Werner
description: A Peco theme
email: 0x142857@gmail.com
feed: true
url: https://peco-theme-tom.netlify.com
theme: ../
themeConfig:
  twitter: _egoistlily
  github: egoist
  nav:
    - title: Home
      link: /
    - title: Peco
      link: https://github.com/egojump/peco